
import { GoogleGenAI, Type } from "@google/genai";

export const config = {
    runtime: 'edge',
};

// 获取所有可用的 API Key
const getAllApiKeys = () => {
    const keys: string[] = [];
    if (process.env.GEMINI_API_KEY) keys.push(process.env.GEMINI_API_KEY);

    // 支持 GEMINI_API_KEY_1 到 GEMINI_API_KEY_31
    for (let i = 1; i <= 31; i++) {
        const key = process.env[`GEMINI_API_KEY_${i}`];
        if (key) keys.push(key);
    }

    // 如果是逗号分隔的格式也支持
    const commaKeys = (process.env.GEMINI_API_KEY || "").split(",").filter(k => k.trim().length > 20);
    commaKeys.forEach(k => {
        if (!keys.includes(k.trim())) keys.push(k.trim());
    });

    return Array.from(new Set(keys)); // 去重
};

// 重试配置
const MAX_RETRIES = 5; // 增加重试次数，因为有更多 Key 可以尝试
const RETRY_DELAY_MS = 1000;

// 延迟函数
const delay = (ms: number) => new Promise(resolve => setTimeout(resolve, ms));

// 判断是否为可重试的错误
const isRetryableError = (error: any): boolean => {
    const message = error?.message?.toLowerCase() || '';
    const status = error?.status || error?.code;

    if (status === 429 || status === 503 || status === 500) return true;
    if (message.includes('rate limit') || message.includes('quota')) return true;
    if (message.includes('overloaded') || message.includes('temporarily')) return true;
    if (message.includes('resource exhausted')) return true;

    return false;
};

export default async function handler(req: Request) {
    if (req.method !== 'POST') {
        return new Response('Method Not Allowed', { status: 405 });
    }

    try {
        const { prompt, images, task } = await req.json();
        const availableKeys = getAllApiKeys();

        if (availableKeys.length === 0) {
            console.error('[Gemini API] No API keys configured');
            return new Response(JSON.stringify({ error: 'Server configuration error: No API keys' }), { status: 500 });
        }

        // Prepare image parts
        const parts = [
            ...(images || []).map((img: any) => ({
                inlineData: {
                    data: img.data.includes(',') ? img.data.split(',')[1] : img.data,
                    mimeType: img.mimeType
                }
            })),
            { text: prompt }
        ];

        let result;
        let lastError: any = null;

        // 带重试和 Key 轮换的 API 调用
        for (let attempt = 1; attempt <= MAX_RETRIES; attempt++) {
            // 每次重试或首次尝试都随机选一个 Key
            const apiKey = availableKeys[Math.floor(Math.random() * availableKeys.length)];
            const ai = new GoogleGenAI({ apiKey });

            try {
                console.log(`[Gemini API] Attempt ${attempt}/${MAX_RETRIES} using random key. Task: ${task}`);

                if (task === 'image') {
                    // 1-图像生成与编辑模型 (gemini-2.5-flash-image)
                    const response = await ai.models.generateContent({
                        model: 'gemini-2.5-flash-image',
                        contents: { parts },
                        config: {
                            responseModalities: ["IMAGE"],
                        }
                    });

                    const part = response.candidates?.[0]?.content?.parts?.[0];
                    if (part && part.inlineData) {
                        result = `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
                    } else {
                        throw new Error("No image generated by gemini-2.5-flash-image");
                    }

                } else if (task === 'validate') {
                    // 验证任务使用稳定版
                    const response = await ai.models.generateContent({
                        model: 'gemini-1.5-flash',
                        contents: { parts },
                        config: {
                            responseMimeType: "application/json",
                            responseSchema: {
                                type: Type.OBJECT,
                                properties: {
                                    hasFace: { type: Type.BOOLEAN },
                                    hasTongue: { type: Type.BOOLEAN }
                                }
                            }
                        }
                    });

                    const text = response.candidates?.[0]?.content?.parts?.[0]?.text;
                    result = JSON.parse(text || "{}");

                } else {
                    // 2-多模态逻辑分析模型 (gemini-3-flash-preview)
                    const response = await ai.models.generateContent({
                        model: 'gemini-3-flash-preview',
                        contents: { parts },
                        config: {
                            responseMimeType: "application/json",
                            responseSchema: {
                                type: Type.OBJECT,
                                properties: {
                                    title: { type: Type.STRING },
                                    score: { type: Type.NUMBER },
                                    content: { type: Type.STRING },
                                    advice: {
                                        type: Type.ARRAY,
                                        items: { type: Type.STRING }
                                    }
                                },
                                required: ["title", "content"]
                            }
                        }
                    });

                    const text = response.candidates?.[0]?.content?.parts?.[0]?.text;
                    result = JSON.parse(text || "{}");
                }

                console.log(`[Gemini API] Success on attempt ${attempt}`);
                break;

            } catch (error: any) {
                lastError = error;
                console.error(`[Gemini API] Attempt ${attempt} failed with key ${apiKey.substring(0, 10)}... :`, error.message);

                if (attempt === MAX_RETRIES || !isRetryableError(error)) {
                    throw error;
                }

                const waitTime = Math.min(RETRY_DELAY_MS * Math.pow(2, attempt - 1), 5000);
                await delay(waitTime);
            }
        }

        return new Response(JSON.stringify(result), {
            status: 200,
            headers: { 'Content-Type': 'application/json' },
        });

    } catch (error: any) {
        console.error('Final API Error:', error);
        let errorMessage = 'AI服务暂不可用，请稍后再试';

        if (error.message?.includes('overloaded') || error.status === 503) {
            errorMessage = '模型负载过高，已尝试多次切换密钥，请在一分钟后再试';
        } else if (error.message?.includes('quota') || error.status === 429) {
            errorMessage = '今日分析额度已达上限，请稍后再试';
        }

        return new Response(JSON.stringify({ error: errorMessage, details: error.message }), { status: 500 });
    }
}
